services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - IS_DOCKER=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Moscow

    depends_on:
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A tt worker --loglevel=info --events --pool=solo --hostname=celery@worker1

    volumes:
      - .:/code
    environment:
      - IS_DOCKER=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Moscow
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A tt beat --loglevel=info
    volumes:
      - .:/code
    environment:
      - IS_DOCKER=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Moscow
    depends_on:
      - redis
      - web

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - IS_DOCKER=True
      - TZ=Europe/Moscow
    depends_on:
      - redis
